# Generated by Django 4.1 on 2022-08-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appBIOEAFIT", "0002_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario", old_name="dieccion", new_name="direccion",
        ),
    ]
