# Generated by Django 4.1 on 2022-08-08 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appBIOEAFIT", "0003_rename_dieccion_usuario_direccion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bonificacion",
            fields=[
                (
                    "idbonificacion",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("valor", models.IntegerField()),
                ("cantidad", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario_Bonificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idbonificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appBIOEAFIT.bonificacion",
                    ),
                ),
                (
                    "identificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appBIOEAFIT.usuario",
                    ),
                ),
            ],
        ),
    ]
