# Generated by Django 4.1 on 2022-08-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appBIOEAFIT", "0004_bonificacion_usuario_bonificacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Botella",
            fields=[
                ("idbotella", models.AutoField(primary_key=True, serialize=False)),
                ("tamanio", models.IntegerField()),
                ("peso", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="bonificacion",
            name="idbonificacion",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Usuario_Botella",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idbotella",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appBIOEAFIT.botella",
                    ),
                ),
                (
                    "identificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appBIOEAFIT.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Puntos_Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "identificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appBIOEAFIT.usuario",
                    ),
                ),
            ],
        ),
    ]
