# Generated by Django 4.1 on 2022-08-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoUsuario",
            fields=[
                (
                    "idtipousuario",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("desctipousuario", models.CharField(max_length=20)),
            ],
        ),
    ]
