# Generated by Django 4.1 on 2022-08-31 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appBIOEAFIT", "0004_bonificacion_usuario_bonificacion"),
    ]

    operations = [
        migrations.RemoveField(model_name="bonificacion", name="cantidad",),
        migrations.AddField(
            model_name="bonificacion",
            name="imagen",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="usuario",
            name="historia",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bonificacion",
            name="idbonificacion",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Puntos_Usuarios",
            fields=[
                ("idpuntos", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                (
                    "identificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appBIOEAFIT.usuario",
                    ),
                ),
            ],
        ),
    ]
