# Generated by Django 4.1 on 2022-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appBIOEAFIT",
            "0005_remove_bonificacion_cantidad_bonificacion_imagen_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bonificacion",
            name="imagen",
            field=models.CharField(default="", max_length=300),
        ),
    ]
