# Generated by Django 4.1 on 2022-08-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBIOEAFIT", "0006_alter_bonificacion_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonificacion",
            name="descripcion",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="usuario", name="historia", field=models.JSONField(null=True),
        ),
    ]
